version: "3.8"

services:

  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db
  nginx:
    container_name: nginx
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    restart: always
    ports:
      - 5020:80
  backend:
    container_name: backend
    build: 
      dockerfile: Dockerfile.dev
      context: ./backend
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always

  frontend:
    container_name: frontend
    build: 
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - 5173:5173
    # restart: always

volumes:
  postgres_data:
